### ISSUE TITLE
I can't use this on Old versions of Python

### ISSUE THREAD

**Issue by maohmaoh** [kujirahand/tkeasygui-python#22]
Python 3.9.13にpipでインストールしました。
Import でエラーが出ます。

```
 Traceback (most recent call last):
  File "c:\Users\user\Documents\Python Scripts\tkeasyguitest.py", line 8, in <module>
    import TkEasyGUI as sg
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\TkEasyGUI\__init__.py", line 5, in <module>
    from TkEasyGUI.dialogs import *  # noqa: F403
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\TkEasyGUI\dialogs.py", line 118, in <module>
    def popup_get_text(message: str, title: str = "", default: str = "", font: tuple[Any]|None=None) -> (str|None):
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```

**Comment by kujirahand** [comment]
すみません。確かに、3.10以降でないと使えないようです。

https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype

`str | None`のようなタイプ宣言をあちらこちらで行っているため、型宣言を削除するしかなさそうです。
どうしようか悩みますね。

**Comment by maohmaoh** [comment]
対応ありがとうございます。
使えるようになりました。
